-- ============================================================
-- ⚠️ ARQUIVO DESATUALIZADO — NÃO USE PARA RECRIAR O BANCO.
--
-- Este arquivo descrevia o schema v1 (question_packs/pack_questions/
-- game_sessions com player_name+difficulty), que foi completamente
-- substituído pelo schema v2 em supabase/migrations/002_funplayb_schema.sql
-- (que já dropa essas tabelas antigas).
--
-- A fonte de verdade do schema atual é a pasta supabase/migrations/,
-- aplicada em ordem numérica. Rode todos os arquivos dessa pasta, em
-- ordem, para reconstruir o banco do zero.
--
-- IMPORTANTE: mesmo as migrations não são 100% completas — algumas
-- colunas/tabelas foram criadas direto no SQL Editor do Supabase sem
-- virar migration (descoberto durante manutenção em 2026-08-14):
--   - public.players.status (character varying(20)) — não existe em
--     nenhuma migration numerada.
--   - public.question_audit e public.theme_cycles — tabelas inteiras
--     usadas pelo app (src/pages/Play.tsx, src/pages/Questions.tsx),
--     mas sem migration correspondente.
-- Se for reconstruir o banco do zero, confirme o schema real direto
-- no painel do Supabase (Table Editor / information_schema) além de
-- rodar as migrations — não confie cegamente só na pasta migrations/.
-- ============================================================
